import enum


class LetterStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    PENDING_PAYMENT = "PENDING_PAYMENT"
    PAID = "PAID"
    SENT = "SENT"
    DELIVERED = "DELIVERED"
    RECEIVED = "RECEIVED"
    FAILED = "FAILED"
    REFUSED = "REFUSED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"


class PaymentStatus(str, enum.Enum):
    PENDING = "PENDING"
    PAID = "PAID"
    FAILED = "FAILED"
    REFUNDED = "REFUNDED"


class DocumentSourceType(str, enum.Enum):
    TEXT_MESSAGE = "TEXT_MESSAGE"
    PDF_UPLOAD = "PDF_UPLOAD"


class ActorType(str, enum.Enum):
    SENDER = "SENDER"
    RECIPIENT = "RECIPIENT"
    ADMIN = "ADMIN"
    SYSTEM = "SYSTEM"


class LetterEventType(str, enum.Enum):
    LETTER_CREATED = "LETTER_CREATED"
    PAYMENT_STARTED = "PAYMENT_STARTED"
    PAYMENT_SUCCEEDED = "PAYMENT_SUCCEEDED"
    PAYMENT_FAILED = "PAYMENT_FAILED"
    LETTER_SENT = "LETTER_SENT"
    EMAIL_SENT = "EMAIL_SENT"
    EMAIL_FAILED = "EMAIL_FAILED"
    RECIPIENT_LINK_ACCESSED = "RECIPIENT_LINK_ACCESSED"
    LETTER_OPENED = "LETTER_OPENED"
    RECEIPT_CONFIRMED = "RECEIPT_CONFIRMED"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    ADMIN_LOGIN = "ADMIN_LOGIN"
    ADMIN_VIEWED_LETTER = "ADMIN_VIEWED_LETTER"
    LETTER_CANCELLED = "LETTER_CANCELLED"
    LETTER_REFUSED = "LETTER_REFUSED"
    # Physical delivery (see app/services/delivery_service.py). Reuses this
    # same audit table/enum rather than a separate delivery_events table --
    # every delivery event is already scoped to exactly one letter.
    DELIVERY_CREATED = "DELIVERY_CREATED"
    DELIVERY_ASSIGNED = "DELIVERY_ASSIGNED"
    DELIVERY_PICKED_UP = "DELIVERY_PICKED_UP"
    DELIVERY_IN_TRANSIT = "DELIVERY_IN_TRANSIT"
    DELIVERY_OUT_FOR_DELIVERY = "DELIVERY_OUT_FOR_DELIVERY"
    DELIVERY_FAILED = "DELIVERY_FAILED"
    DELIVERY_DEPOSITED = "DELIVERY_DEPOSITED"
    DELIVERY_DELIVERED = "DELIVERY_DELIVERED"
    DELIVERY_RETURNED = "DELIVERY_RETURNED"
    DELIVERY_CANCELLED = "DELIVERY_CANCELLED"


class EmailType(str, enum.Enum):
    PAYMENT_CONFIRMATION = "PAYMENT_CONFIRMATION"
    RECIPIENT_NOTIFICATION = "RECIPIENT_NOTIFICATION"
    LETTER_OPENED = "LETTER_OPENED"
    RECEIPT_CONFIRMED = "RECEIPT_CONFIRMED"
    SYSTEM_ERROR = "SYSTEM_ERROR"
    DELIVERY_CONFIRMATION_REQUEST = "DELIVERY_CONFIRMATION_REQUEST"
    DELIVERY_CONFIRMED_RECIPIENT = "DELIVERY_CONFIRMED_RECIPIENT"
    DELIVERY_CONFIRMED_SENDER = "DELIVERY_CONFIRMED_SENDER"


class EmailStatus(str, enum.Enum):
    PENDING = "PENDING"
    SENT = "SENT"
    FAILED = "FAILED"


class DeliveryStatus(str, enum.Enum):
    """Detailed physical-delivery state machine -- separate from, but linked
    to, LetterStatus (see app/services/delivery_state.py). Only DELIVERED
    means the physical letter actually reached the recipient."""

    CREATED = "CREATED"
    READY_FOR_DISPATCH = "READY_FOR_DISPATCH"
    ASSIGNED = "ASSIGNED"
    PICKED_UP = "PICKED_UP"
    IN_TRANSIT = "IN_TRANSIT"
    OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY"
    DEPOSITED = "DEPOSITED"
    DELIVERED = "DELIVERED"
    DELIVERY_FAILED = "DELIVERY_FAILED"
    RETURNED_TO_SENDER = "RETURNED_TO_SENDER"
    CANCELLED = "CANCELLED"


class DeliveryProviderType(str, enum.Enum):
    INTERNAL = "INTERNAL"
    EXTERNAL_CARRIER = "EXTERNAL_CARRIER"
    POSTAL_SERVICE = "POSTAL_SERVICE"


class ProofOfDeliveryType(str, enum.Enum):
    MANUAL_CONFIRMATION = "MANUAL_CONFIRMATION"
    SIGNATURE = "SIGNATURE"
    OTP = "OTP"
    PHOTO = "PHOTO"
    EXTERNAL_PROVIDER_CONFIRMATION = "EXTERNAL_PROVIDER_CONFIRMATION"


class DeliveryFailureReason(str, enum.Enum):
    RECIPIENT_UNAVAILABLE = "RECIPIENT_UNAVAILABLE"
    INCORRECT_ADDRESS = "INCORRECT_ADDRESS"
    RECIPIENT_REFUSED = "RECIPIENT_REFUSED"
    ADDRESS_INACCESSIBLE = "ADDRESS_INACCESSIBLE"
    OTHER = "OTHER"
