import enum


class LetterStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    PENDING_PAYMENT = "PENDING_PAYMENT"
    PAID = "PAID"
    SENT = "SENT"
    DELIVERED = "DELIVERED"
    OPENED = "OPENED"
    RECEIVED = "RECEIVED"
    FAILED = "FAILED"
    REFUSED = "REFUSED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"


class PaymentStatus(str, enum.Enum):
    PENDING = "PENDING"
    PAID = "PAID"
    FAILED = "FAILED"
    REFUNDED = "REFUNDED"


class DocumentSourceType(str, enum.Enum):
    TEXT_MESSAGE = "TEXT_MESSAGE"
    PDF_UPLOAD = "PDF_UPLOAD"


class ActorType(str, enum.Enum):
    SENDER = "SENDER"
    RECIPIENT = "RECIPIENT"
    ADMIN = "ADMIN"
    SYSTEM = "SYSTEM"


class LetterEventType(str, enum.Enum):
    LETTER_CREATED = "LETTER_CREATED"
    PAYMENT_STARTED = "PAYMENT_STARTED"
    PAYMENT_SUCCEEDED = "PAYMENT_SUCCEEDED"
    PAYMENT_FAILED = "PAYMENT_FAILED"
    LETTER_SENT = "LETTER_SENT"
    EMAIL_SENT = "EMAIL_SENT"
    EMAIL_FAILED = "EMAIL_FAILED"
    RECIPIENT_LINK_ACCESSED = "RECIPIENT_LINK_ACCESSED"
    LETTER_OPENED = "LETTER_OPENED"
    RECEIPT_CONFIRMED = "RECEIPT_CONFIRMED"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    ADMIN_LOGIN = "ADMIN_LOGIN"
    ADMIN_VIEWED_LETTER = "ADMIN_VIEWED_LETTER"
    LETTER_CANCELLED = "LETTER_CANCELLED"
    LETTER_REFUSED = "LETTER_REFUSED"


class EmailType(str, enum.Enum):
    PAYMENT_CONFIRMATION = "PAYMENT_CONFIRMATION"
    RECIPIENT_NOTIFICATION = "RECIPIENT_NOTIFICATION"
    LETTER_OPENED = "LETTER_OPENED"
    RECEIPT_CONFIRMED = "RECEIPT_CONFIRMED"
    SYSTEM_ERROR = "SYSTEM_ERROR"


class EmailStatus(str, enum.Enum):
    PENDING = "PENDING"
    SENT = "SENT"
    FAILED = "FAILED"
