"""physical delivery system

Revision ID: eb4a50b374cf
Revises: 16b32a1691c8
Create Date: 2026-09-11 14:29:13.733625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb4a50b374cf'
down_revision: Union[str, None] = '16b32a1691c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_providers',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider_type', sa.Enum('INTERNAL', 'EXTERNAL_CARRIER', 'POSTAL_SERVICE', name='delivery_provider_type'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('api_enabled', sa.Boolean(), nullable=False),
    sa.Column('api_base_url', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('delivery_agents',
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['delivery_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_agents_provider_id'), 'delivery_agents', ['provider_id'], unique=False)
    op.create_table('delivery_orders',
    sa.Column('letter_id', sa.UUID(), nullable=False),
    sa.Column('tracking_number', sa.String(length=32), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('courier_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'READY_FOR_DISPATCH', 'ASSIGNED', 'PICKED_UP', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED', 'DELIVERY_FAILED', 'RETURNED_TO_SENDER', 'CANCELLED', name='delivery_status'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('picked_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('in_transit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('out_for_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['courier_id'], ['delivery_agents.id'], ),
    sa.ForeignKeyConstraint(['letter_id'], ['letters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['delivery_providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('letter_id')
    )
    op.create_index(op.f('ix_delivery_orders_courier_id'), 'delivery_orders', ['courier_id'], unique=False)
    op.create_index(op.f('ix_delivery_orders_provider_id'), 'delivery_orders', ['provider_id'], unique=False)
    op.create_index(op.f('ix_delivery_orders_status'), 'delivery_orders', ['status'], unique=False)
    op.create_index(op.f('ix_delivery_orders_tracking_number'), 'delivery_orders', ['tracking_number'], unique=True)
    op.create_table('delivery_attempts',
    sa.Column('delivery_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('courier_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Enum('RECIPIENT_UNAVAILABLE', 'INCORRECT_ADDRESS', 'RECIPIENT_REFUSED', 'ADDRESS_INACCESSIBLE', 'OTHER', name='delivery_failure_reason'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['courier_id'], ['delivery_agents.id'], ),
    sa.ForeignKeyConstraint(['delivery_id'], ['delivery_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_attempts_delivery_id'), 'delivery_attempts', ['delivery_id'], unique=False)
    op.create_table('proofs_of_delivery',
    sa.Column('delivery_id', sa.UUID(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_by', sa.String(length=255), nullable=False),
    sa.Column('recipient_name_if_provided', sa.String(length=200), nullable=True),
    sa.Column('delivery_method', sa.String(length=100), nullable=True),
    sa.Column('proof_type', sa.Enum('MANUAL_CONFIRMATION', 'SIGNATURE', 'OTP', 'PHOTO', 'EXTERNAL_PROVIDER_CONFIRMATION', name='proof_of_delivery_type'), nullable=False),
    sa.Column('proof_reference', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['delivery_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_id')
    )
    # ### end Alembic commands ###

    # Seed the phase-1 internal/manual provider. delivery_service.py looks
    # this up by its stable `code` ("courrier_plus_internal") -- every new
    # DeliveryOrder is assigned to it until a real external carrier is added.
    # A fixed literal UUID avoids depending on the pgcrypto extension for
    # gen_random_uuid() being enabled.
    op.execute(
        """
        INSERT INTO delivery_providers (id, code, name, provider_type, active, api_enabled, created_at, updated_at)
        VALUES ('31bcd9dc-dbb3-487e-ae62-79a6bd4a0143', 'courrier_plus_internal', 'Courrier+ Delivery', 'INTERNAL', true, false, now(), now())
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proofs_of_delivery')
    op.drop_index(op.f('ix_delivery_attempts_delivery_id'), table_name='delivery_attempts')
    op.drop_table('delivery_attempts')
    op.drop_index(op.f('ix_delivery_orders_tracking_number'), table_name='delivery_orders')
    op.drop_index(op.f('ix_delivery_orders_status'), table_name='delivery_orders')
    op.drop_index(op.f('ix_delivery_orders_provider_id'), table_name='delivery_orders')
    op.drop_index(op.f('ix_delivery_orders_courier_id'), table_name='delivery_orders')
    op.drop_table('delivery_orders')
    op.drop_index(op.f('ix_delivery_agents_provider_id'), table_name='delivery_agents')
    op.drop_table('delivery_agents')
    op.drop_table('delivery_providers')
    # ### end Alembic commands ###
